redux toolkitの導入
yasufumimyoi/nextjs-project pull request #1
Opened 2021-06-23 07:47 UTC by yasufumimyoi

useContext・useReducerから置き換えました。
storeの中にはアニメのデータとユーザーのログイン・ユーザー情報を入れています。

2021-06-23 08:23 UTC, fiftie requested changes
レビューしましたー！
コメントしたところは、他の部分にも当てはまるかもしれないので、もう一度自身でコードを見直して見てください。

また差分が大きくて、レビュー大変だったのでできれば細かくコミットしてPRを出してもらえると助かります笑

2021-06-23 08:23 UTC, fiftie commented on anime.ts
> +  data: Datum[];
:nits
`Datum` はここよりも後ろのL7で定義されているのであまりよろしくないです。
参照する前に定義しましょうー

2021-06-23 08:23 UTC, fiftie commented on anime.ts
> +  nsfw: boolean;
こんなにたくさんのプロパティが必要ですか？？
使う分だけ定義して、シンプルにしましょう

2021-06-23 08:23 UTC, fiftie commented on anime.ts
> +  abbreviatedTitles: any[];
せっかくTypeScriptを使っているので、`any` はやめましょう。

2021-06-23 08:23 UTC, fiftie commented on anime.ts
> +  nextRelease: null;
`null` しか入らないプロパティは必要ないので、消しましょう！

2021-06-23 08:23 UTC, fiftie commented on anime.ts
> +  nsfw: boolean;
`boolean` が入る変数やプロパティの名前はis~のような名前が一般的です。

2021-06-23 08:23 UTC, fiftie commented on anime.ts
> +export interface Large {
`Large` という名前は適切ですかね？？
例えば `Rect` とかのほうが想像しやすいかも

2021-06-23 08:23 UTC, fiftie commented on components/Auth.js
> +  };
コンポーネントに非同期処理を書くとコードが肥大化しちゃうので、redux-thunkを使って書いたほうが良いかもです。
redux-thunkはRedux-toolkitに含まれているので、調べてみてください

2021-06-23 08:23 UTC, fiftie commented on components/Auth.js
> +  return <div></div>;
意味のあるviewを返さないコンポーネントはつくらないようにしましょう。
おそらくここらへんの処理は他に移管できるはずです。

FYI:
ちなみに仕方なく何も返したくない場合はフラグメントを使えます。
``` TSX
return <></>;
```

2021-06-23 08:23 UTC, fiftie commented on components/Auth.js
> +        if (!users) {
:nits
`users` があるかどうかを調べてから、firebase周りの処理をしたほうがスッキリします。
`user` だったり `users` という似た名前がごっちゃになってしまっているので、もう少しわかりやすい名前をつけたいですね！

2021-06-23 08:23 UTC, fiftie commented on components/Detail.js
> +                    onClick={() => writeData(result.data[0])}
`result.data[0]` は正しい？？
`detail` を使いたい

2021-06-23 08:23 UTC, fiftie commented on components/HeaderItem.js
>  };
:nits
こう書き換えられます
``` TSX
const HeaderItem = ({ Icon, title }) => (
    <div className="flex flex-col items-center group hover:opacity-50 duration-300">
      <Icon className="h-5 text-purple-500 group-hover:animate-bounce mb-1" />
      <p className="text-xs">{title}</p>
    </div>
  );
```

2021-06-23 08:23 UTC, fiftie commented on redux/user.js
> +    users: null,
`users` は複数形だから配列？
であればnullではなく空配列にしたほうが色々便利ですよ！

2021-06-25 10:19 UTC, fiftie requested changes
またしても量が多かったので、ざっと見ました！
TypeScriptに移行した辺りから、ガッツリ業務レベルで見ようか悩んでます。
希望あればどうぞ

2021-06-25 10:19 UTC, fiftie commented on components/Auth.js
> +        dispatch(setUid(user.uid));
`user` のプロパティを使うことが多いので、分割代入で変数作っておくと可読性が増します。
```ts
const { uid, isAnonymous } = user;
```

2021-06-25 10:19 UTC, fiftie commented on pages/index.js
> +        movie.attributes.titles.ja_jp != undefined &&
`undefined` や `null` のチェックなら比較しなくていいです
```ts
movie.attributes.titles.ja_jp && movie.attributes.ratingRank
```

2021-06-25 10:19 UTC, fiftie commented on pages/index.js
> +    }
1. `let` ではなく `const` をなるべく使う
2. 多分 `map` をつかってもっとスマートに書ける

2021-06-25 10:19 UTC, fiftie commented on pages/list.js
> +            <Card movie={movie} key={movie.title + index + movie.id} />
`key` は `id` だけでいいかも

2021-06-25 10:19 UTC, fiftie commented on pages/result/index.js
> +        filteredData.push(temp);
`map` のなかで`push` しない

2021-06-25 10:19 UTC, fiftie commented on redux/movie.js
> +  },
理由は省きますが、`builder` を使ったほうがTypeScriptに移行したときに書き換えコストが少なくなる
https://redux-toolkit.js.org/api/createSlice#extrareducers

2021-06-25 10:19 UTC, fiftie commented on redux/user.js
> +);
firebaseへのアクセスを`createAsyncThunk` でやるか、コンポーネントでやるか割れてるので、どっちかに統一したほうが良いと思いますー
おすすめは前者

2021-06-25 10:19 UTC, fiftie commented on redux/user.js
> +    uid: null,
もしstringなら初期値は空文字のほうが良いかもしれません

2021-06-25 10:19 UTC, fiftie commented on redux/user.js
>        state.login = true;
booleanが入るので、`isLogin` って名前のstateにしたほうがわかりやすいかもっす。
booleanのときは `is~` っていう命名にするのが暗黙の了解です

2021-06-26 08:02 UTC, yasufumimyoi commented on pages/index.js
> +        movie.attributes.titles.ja_jp != undefined &&
APIドキュメントを見て色々とクエリを試行錯誤したのですが、取り出したいデータのみ抽出できなかったので、こちらのコードを入れています。
海外のAPIを使用しているので、アメコミや中国アニメは弾きたいのでtitlesを日本語のみ。
また日本語のタイトルでもRatingが無いものだと聞いた事がないようなアニメやまだ未公開のアニメも入るのでratingもチェックして弾いております。
無くした場合の戻り値の画像を添付させて頂きます

URL: https://kitsu.docs.apiary.io/#reference/anime/anime
![スクリーンショット 2021-06-26 16 22 09](https://user-images.githubusercontent.com/61864641/123506618-1a57b880-d6a0-11eb-8468-3e7596a79261.png)

2021-06-27 04:00 UTC, fiftie requested changes
コメントしましたー
まだ前回のコメントを反映できていないところがあるので、確認してください

2021-06-27 04:00 UTC, fiftie commented on pages/result/index.js
> +    selectedData = data.data.map((movie) => {
`data.data` って奇妙ですね。。。
データ構造が悪いか、変数の命名が微妙なので、見直してみてください

2021-06-27 04:00 UTC, fiftie commented on pages/result/index.js
> +      item["status"] = movie.attributes.status;
こんな感じで書けそう。
三点リーダは省略の意味なので、実際には正しい文字に置き換えてください
``` js
const { titles, posterImage, ...} = movie.attributes;
return {
  id: movie.id,
  title: titles.ja_jp,
...
}
```

2021-06-27 04:00 UTC, fiftie commented on redux/user.js
> +    isLogin: (state) => {
ああ、アクションは `setLogin`のままでいいです。
stateのほうだけ `isLogin` の方がいいかと

2021-06-28 02:38 UTC, fiftie requested changes
コメントしましたー

2021-06-28 02:38 UTC, fiftie commented on pages/index.js
> +        movie.attributes.titles.ja_jp != undefined &&
`undefined` や `null` はfalseとして扱われるので、比較しなくてもいいという意味です！

2021-06-28 02:38 UTC, fiftie commented on pages/index.js
> +        movie.attributes.titles.ja_jp != undefined &&
ここらへんを勉強されると良いかもっす
https://developer.mozilla.org/ja/docs/Glossary/Falsy

2021-06-28 02:38 UTC, fiftie commented on components/Card.js
> +                ? movie.averageRating + "%"
変数と文字列を結合するときは、以下の書き方がメジャーです
```jsx
`${movie.averageRating}%`
```

2021-06-28 02:38 UTC, fiftie commented on components/Header.js
> +import { removeLogin, removeUid, removeProfile } from "../redux/user";
`removeLogin` ってつまりログアウト？
であれば `logout` でいいのでは

2021-06-28 02:38 UTC, fiftie commented on firebase/function.js
> +        status,
good!

2021-06-28 02:38 UTC, fiftie commented on firebase/function.js
>        .doc(movie.id)
ここも `id` だけで大丈夫

2021-06-28 02:38 UTC, fiftie commented on pages/index.js
> +      const { id } = movie;
こう書けるかも
``` js
const selectedData = validTitles.map(({ id, attributes }) => {
  const { titles, posterImage, averageRating, episodeLength, status } = attributes;
```

2021-06-28 02:38 UTC, fiftie commented on pages/index.js
> +    };
ここらへん他のところでも同じ箇所があると思うので、一個にまとめたいっすね
`redux-thunk` にロジック移して、returnする値はstoreに持たせればいいかも

2021-06-30 10:10 UTC, fiftie requested changes
コメントしましたー

同じところ何回かコメントしてるかもですが、コードがきれいになっていくごとに新たなもっと良い書き方を思いつくことは日常茶飯事なので慣れてください笑

だいぶ良くなってきましが、まだロジックをコンポーネントで持っている箇所が多くて気になります。
ただそこはTypeScriptに移行したあとに直すでも良いと思うので、コメントはしていません。

2021-06-30 10:10 UTC, fiftie commented on components/Card.js
> +                : "データがありません"}
こうで良い気がしてきた
```tsx
{movie.averageRating
  ? `${movie.averageRating}%`
  : "データがありません"}
```

2021-06-30 10:10 UTC, fiftie commented on components/Detail.js
>                          : "データがありません"}
ここも

2021-06-30 10:10 UTC, fiftie commented on components/Header.js
> +          dispath(Logout());
他と合わせて頭文字小文字の方がいいかもです

2021-06-30 10:10 UTC, fiftie commented on pages/index.js
> +    });
`movies` って他のところでも使っているから、storeにおいた方が良いように思います。
thenの処理も不要になるし。

2021-06-30 10:10 UTC, fiftie commented on pages/list.js
> +          movieList.map((movie) => <Card movie={movie} key={movie.id} />)
0はfalsyだから比較しなくても大丈夫

2021-06-30 10:10 UTC, fiftie commented on pages/result/[id].js
> +  });
mapだからもしかしたらメモ化したほうが良いかも。

それから、こんな感じでリファクタできるかも
関係ないプロパティもリターンしちゃうけど、記述はスッキリするからあとは好みかな
```tsx
const selectedData = validTitles.map(({ id, attributes }) => (
  {...attributes, title: attributes.titles.ja_jp, image: attributes.posterImage.original}
);
```

2021-06-30 10:10 UTC, fiftie commented on redux/movie.js
> +      let temp = state.movieList.filter((movie) => movie !== null);
const?

2021-07-02 02:17 UTC, fiftie requested changes
コメントしましたー
メモ化について誤解を与えてしまってすみません

2021-07-02 02:17 UTC, fiftie commented on pages/index.js
> +  }));
いいっすね！
こんな感じで短く書けるのが関数型言語の良い点なので、常にきれいに短く書ける方法がないか考えながら書きましょうー
とくに配列やオブジェクトはより良い方法が見つかりやすいです

2021-07-02 02:17 UTC, fiftie commented on pages/result/[id].js
> +);
あー、なるほどすみません。
もしかしたら前回の指摘は `getInitialProps` のmapに関して、メモ化できると言っていたかもしれないです
メモ化は基本的にコンポーネントの中のロジックに対して行うので、今回は不要です。
今回の `Result` はそれほど頻繁に (毎秒何回もとか) 変更されないと思うので、メモ化は不要です。
それから基本的にメモ化は `useMemo` を使うので、それも抑えたほうが良いかもしれません。

2021-07-02 02:17 UTC, fiftie commented on redux/movie.js
> +      //検索されたkeywordの切り出し
検索されたキーワードってURLからしか取得できないんですかね？
例えばstoreとかに入れておけば楽そうと思いました

2021-07-02 02:17 UTC, fiftie commented on redux/movie.js
> +        });
mapでシンプルに書けそう
forEachはまず使わないので、もし使うときは別の手段がないか疑問に持ちましょう

2021-07-02 02:17 UTC, fiftie commented on redux/movie.js
> +        return selectedData;
もっと短くできます！

2021-07-02 02:17 UTC, fiftie commented on pages/result/index.js
>              ))
メモ化するならこういうところです！

2021-07-03 13:30 UTC, fiftie reviewed
見ました！
概ね良いと思います。

また、アドバイスが勉強になっているようで良かったです。
これからもこんな調子でレビューしていきますね

2021-07-03 13:30 UTC, fiftie commented on pages/result/index.js
> +  }, [results.length]);
```suggestion
  const MemorizedCard = useMemo(() => (
    movies.map((video) => <Card movie={video} key={movie.title + index} />)
  ), [results]);
```

2021-07-03 13:30 UTC, fiftie commented on redux/movie.js
> +          .map(({ id, attributes }) => {
こんなふうにも書けます
やりすぎるとかえって分かりづらくなるので、修正するかどうかは任せます！
```js
{ id, attributes: { titles, posterImage } }
```

2021-07-03 13:30 UTC, fiftie commented on redux/movie.js
> +          .filter((video) => video !== undefined);
```js
.filter((video) => video);
```

2021-07-03 13:30 UTC, fiftie commented on redux/movie.js
> +        return selectedData;
`selectedData` という変数をわざわざつくらず、直でリターンしても良いかもですね
細かいですが

2021-07-05 02:34 UTC, fiftie approved these changes
LGTM

エンジニアとして働かれていくということで、おめでとうございますー！
TypeScriptへの切り替えは一気にやっちゃって良いのではないでしょうか。
途中でPR出していただきてもいいですし、おまかせしますー
TS導入したら、厳し目にPRレビューします。

2021-07-05 06:19 UTC, merged